services:
  product-service:
    build: ./product-service
    ports: 
      - "${PRODUCT_SERVICE_PORT}:3000"
    env_file:
      - .env
    environment:
      DB_HOST: ${PRODUCT_DB_HOST}
      DB_NAME: ${PRODUCT_DB_NAME}
      DB_USER: ${PRODUCT_DB_USER}
      DB_PASSWORD: ${PRODUCT_DB_PASSWORD}
    container_name: product-service
    restart: always
    depends_on:
      - product-db
  
  product-db:
    image: mysql:8.0.36
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD : ${PRODUCT_DB_PASSWORD}
      MYSQL_DATABASE : ${PRODUCT_DB_NAME}
    volumes:
      - product-db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: product-db
      MYSQL_ROOT_PASSWORD: ${PRODUCT_DB_PASSWORD}
    depends_on:
      - product-db
    restart: always

  cart-service:
   build: ./cart-service
   container_name: cart-service
   ports:
    - "3001:3001"
   environment:
    DB_HOST: cart-db
    DB_NAME: cart_db
    DB_USER: root
    DB_PASSWORD: cartpassword
    PORT: 3001
   depends_on:
    - cart-db
   restart: always
 
  cart-db:
   image: mysql:8.0.36
   environment:
      MYSQL_ROOT_PASSWORD: cartpassword
      MYSQL_DATABASE: cart_db
   volumes:
    - cart-db-data:/var/lib/mysql
   restart: always


  

  review-service:
    build: ./review-services
    container_name: review-service
    ports:
      - "5002:5002"
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://admin:admin123@mongo-db:27017/reviewdb?authSource=admin
    depends_on:
      - mongo-db
    restart: always

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      DB_HOST: user-db
      DB_PORT: 5432
      DB_NAME: ${USER_DB_NAME}
      DB_USER: ${USER_DB_USER}
      DB_PASSWORD: ${USER_DB_PASSWORD}
    depends_on:
      - user-db
    restart: always

  user-db:
    image: postgres:16
    container_name: user-db
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data
    restart: always
    
  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo-db-data:/data/db
    restart: always

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    env_file:
      - .env
    environment:
      ME_CONFIG_BASICAUTH: "true"
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo-db:27017/?authSource=admin
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    restart: always
    depends_on:
      - mongo-db

volumes:
  product-db-data:
  mongo-db-data:
  user-db-data:
  cart-db-data:
